(function () {

    /* ============================================
       HOW TO ADD A GAME
       1) Put the game folder inside Games/   (it needs an index.html inside)
       2) Put its logo inside images/         (name it like the folder in lowercase,
                                               for example  slope.png  or  bad-ice-cream.jpg)
       3) Add one line to the list below:     { folder: 'slope' },
       Only add  entry: '...'  if the game starts from a file other than index.html.
       ============================================ */

    var games = [
        { folder: '1' },
        { folder: '10-minutes-till-dawn' },
        { folder: '100ng' },
        { folder: '1v1lol' },
        { folder: '1v1space' },
        { folder: '2048' },
        { folder: '2048-multitask' },
        { folder: '9007199254740992' },
        { folder: '99balls' },
        { folder: 'a-dance-of-fire-and-ice' },
        { folder: 'achievementunlocked' },
        { folder: 'adarkroom' },
        { folder: 'adrenalinechallenge' },
        { folder: 'adventure-drivers' },
        { folder: 'ages-of-conflict' },
        { folder: 'alienhominid' },
        { folder: 'align-4' },
        { folder: 'amazing-rope-police' },
        { folder: 'amidst-the-clouds' },
        { folder: 'among-us' },
        { folder: 'angelunder' },
        { folder: 'angry-sharks' },
        { folder: 'aquapark-slides' },
        { folder: 'astray' },
        { folder: 'avalanche' },
        { folder: 'awesometanks2' },
        { folder: 'backrooms' },
        { folder: 'backrooms-2d' },
        { folder: 'backrooms2d' },
        { folder: 'bacon-may-die' },
        { folder: 'bad-ice-cream' },
        { folder: 'bad-ice-cream-2' },
        { folder: 'bad-ice-cream-3' },
        { folder: 'baldis-basics' },
        { folder: 'balldodge' },
        { folder: 'ballistic-chickens' },
        { folder: 'basket-random' },
        { folder: 'basketball-stars' },
        { folder: 'basketbros-io' },
        { folder: 'battleforgondor' },
        { folder: 'bigredbutton' },
        { folder: 'bitlife' },
        { folder: 'blacholesquare' },
        { folder: 'blackknight' },
        { folder: 'blockpost' },
        { folder: 'bloonstd' },
        { folder: 'bloonstd2' },
        { folder: 'bloxors' },
        { folder: 'bntts' },
        { folder: 'bobtherobber2' },
        { folder: 'bonkio' },
        { folder: 'boxhead2play' },
        { folder: 'boxing-random' },
        { folder: 'breakingthebank' },
        { folder: 'btd4' },
        { folder: 'btd5' },
        { folder: 'btts' },
        { folder: 'burger-and-frights' },
        { folder: 'bus and subway' },
        { folder: 'cannon-basketball-4' },
        { folder: 'canyondefense' },
        { folder: 'cars-simulator' },
        { folder: 'cell-machine' },
        { folder: 'champion-island' },
        { folder: 'championarcher' },
        { folder: 'checkers' },
        { folder: 'chess' },
        { folder: 'chill-radio' },
        { folder: 'chrome-dino' },
        { folder: 'circlo' },
        { folder: 'classicube' },
        { folder: 'cluster-rush' },
        { folder: 'cnpingpong' },
        { folder: 'connect3' },
        { folder: 'cookie-clicker' },
        { folder: 'core-ball' },
        { folder: 'craftmine' },
        { folder: 'creativekillchamber' },
        { folder: 'crossyroad' },
        { folder: 'csgo-clicker' },
        { folder: 'ctr' },
        { folder: 'ctr-holiday' },
        { folder: 'ctr-tr' },
        { folder: 'cubefield' },
        { folder: 'cupcake2048' },
        { folder: 'dante' },
        { folder: 'deal-or-no-deal' },
        { folder: 'death-run-3d' },
        { folder: 'deepest-sword' },
        { folder: 'defend-the-tank' },
        { folder: 'doctor-acorn2' },
        { folder: 'dodge' },
        { folder: 'doge2048' },
        { folder: 'DogeMiner' },
        { folder: 'Dogeminer2' },
        { folder: 'doodle-jump' },
        { folder: 'doom' },
        { folder: 'DOOMORI' },
        { folder: 'doublewires' },
        { folder: 'dragon-vs-bricks' },
        { folder: 'draw-the-hill' },
        { folder: 'drift-boss' },
        { folder: 'drift-hunters' },
        { folder: 'drive-mad' },
        { folder: 'ducklife1' },
        { folder: 'ducklife2' },
        { folder: 'ducklife3' },
        { folder: 'ducklife4' },
        { folder: 'duke-nukem-2' },
        { folder: 'dumbwaystodie' },
        { folder: 'eaglerfaithful' },
        { folder: 'eaglerjp' },
        { folder: 'earntodie' },
        { folder: 'edge-surf' },
        { folder: 'edgenotfound' },
        { folder: 'eel-slap' },
        { folder: 'eggycar' },
        { folder: 'elasticman' },
        { folder: 'endlesswar3' },
        { folder: 'escapingtheprison' },
        { folder: 'evil-glitch' },
        { folder: 'evolution' },
        { folder: 'exo' },
        { folder: 'factoryballs' },
        { folder: 'fairsquares' },
        { folder: 'fake-virus' },
        { folder: 'fancypantsadventures' },
        { folder: 'fantasy-dash' },
        { folder: 'fireboywatergirlforesttemple' },
        { folder: 'flappy plane' },
        { folder: 'flappy-2048' },
        { folder: 'flappy-bird' },
        { folder: 'flappybird' },
        { folder: 'flashtetris' },
        { folder: 'fleeingthecomplex' },
        { folder: 'flippy-fish' },
        { folder: 'fnaw' },
        { folder: 'fridaynightfunkin' },
        { folder: 'froggys-battle' },
        { folder: 'fruitninja' },
        { folder: 'frying-nemo' },
        { folder: 'fsucraft' },
        { folder: 'fuclient' },
        { folder: 'gachalife' },
        { folder: 'game-inside' },
        { folder: 'gdtd' },
        { folder: 'gearsofbabies' },
        { folder: 'generic-fishing-game' },
        { folder: 'geochallenge' },
        { folder: 'geodash' },
        { folder: 'geodashlite' },
        { folder: 'geogeo' },
        { folder: 'geojump' },
        { folder: 'geoneondash' },
        { folder: 'geops1' },
        { folder: 'georash' },
        { folder: 'georgeandtheprinter' },
        { folder: 'geotrash' },
        { folder: 'getaway-shootout' },
        { folder: 'gimme-the-airpod' },
        { folder: 'glass-city' },
        { folder: 'gmonster' },
        { folder: 'go-ball' },
        { folder: 'goodnight' },
        { folder: 'goodnight-meowmie' },
        { folder: 'google-feud' },
        { folder: 'google-snake' },
        { folder: 'gravity-soccer' },
        { folder: 'greybox' },
        { folder: 'grindcraft' },
        { folder: 'hackertype' },
        { folder: 'handshakes' },
        { folder: 'happy-hop' },
        { folder: 'happywheels' },
        { folder: 'hardware-tycoon' },
        { folder: 'hba' },
        { folder: 'helicopter' },
        { folder: 'hellscaper', entry: 'Hellscaper WebGL 4-19-23/index.html' },
        { folder: 'hexempire' },
        { folder: 'HexGL' },
        { folder: 'hextris' },
        { folder: 'highrisehop' },
        { folder: 'hill-climb-racing' },
        { folder: 'hungry-lamu' },
        { folder: 'iceagebaby' },
        { folder: 'iceagebaby2' },
        { folder: 'idle-breakout' },
        { folder: 'idle-shark' },
        { folder: 'idledice' },
        { folder: 'idledices' },
        { folder: 'impossiblequiz' },
        { folder: 'interactivebuddy' },
        { folder: 'invite-the-blackbird' },
        { folder: 'jetpack-joyride' },
        { folder: 'just-fall' },
        { folder: 'just-one-boss' },
        { folder: 'kitchen-gun-game' },
        { folder: 'kittencannon' },
        { folder: 'knife-master' },
        { folder: 'krunker' },
        { folder: 'learntofly' },
        { folder: 'learntofly2' },
        { folder: 'legacyflashgames', entry: 'sesame/games/abbys-sandbox-search/index.html' },
        { folder: 'level13' },
        { folder: 'ltf3' },
        { folder: 'madalin-stunt-cars-2' },
        { folder: 'madalin-stunt-cars-3' },
        { folder: 'marvinspectrum' },
        { folder: 'meme2048' },
        { folder: 'merge-round-racers' },
        { folder: 'mindustry' },
        { folder: 'mineblocks' },
        { folder: 'minecraft-15' },
        { folder: 'minecraft-classic' },
        { folder: 'minecraftbeta' },
        { folder: 'minesweeper', entry: 'beginner/index.html' },
        { folder: 'missiles' },
        { folder: 'MonkeyMart' },
        { folder: 'monster-tracks' },
        { folder: 'motox3m-pool' },
        { folder: 'motox3m-spooky' },
        { folder: 'motox3m-winter' },
        { folder: 'motox3m2' },
        { folder: 'my-rusty-submarine' },
        { folder: 'n-gon' },
        { folder: 'ninja' },
        { folder: 'ninjavsevilcorp' },
        { folder: 'noob-steve-parkour' },
        { folder: 'ns-shaft' },
        { folder: 'nsresurgence' },
        { folder: 'OfflineParadise' },
        { folder: 'om-bounce' },
        { folder: 'osu!' },
        { folder: 'papaspizzaria' },
        { folder: 'particle-clicker' },
        { folder: 'pixel-gun-survival' },
        { folder: 'planetlife' },
        { folder: 'poom' },
        { folder: 'popcat-classic' },
        { folder: 'precision-client' },
        { folder: 'protektor' },
        { folder: 'push-the-square' },
        { folder: 'push-your-luck' },
        { folder: 'rabbit-samurai' },
        { folder: 'rabbit-samurai2' },
        { folder: 'resent-client', entry: '1.8/index.html' },
        { folder: 'riddleschool' },
        { folder: 'riddleschool2' },
        { folder: 'riddleschool3' },
        { folder: 'riddleschool4' },
        { folder: 'riddleschool5' },
        { folder: 'riddletransfer' },
        { folder: 'riddletransfer2' },
        { folder: 'roblox' },
        { folder: 'roblox copy' },
        { folder: 'Rocket-League' },
        { folder: 'rolling-forests' },
        { folder: 'rolly-vortex' },
        { folder: 'rooftop-snipers' },
        { folder: 'roommate', entry: '31/index.html' },
        { folder: 'Run 2' },
        { folder: 'run4bootleg' },
        { folder: 'runner' },
        { folder: 'sand-game' },
        { folder: 'santy-is-home' },
        { folder: 'scooperia' },
        { folder: 'scratcharia' },
        { folder: 'ShapeShootout' },
        { folder: 'shellshockers' },
        { folder: 'shotinthedark' },
        { folder: 'shuttledeck' },
        { folder: 'sky-car-stunt' },
        { folder: 'sleepingbeauty' },
        { folder: 'slime-rush-td' },
        { folder: 'slope' },
        { folder: 'slope-ball' },
        { folder: 'smashkarts' },
        { folder: 'smokingbarrels' },
        { folder: 'snowbattle' },
        { folder: 'snowrider3d' },
        { folder: 'soccer-random' },
        { folder: 'soccer-skills' },
        { folder: 'soldier-legend' },
        { folder: 'solitaire' },
        { folder: 'sort-the-court' },
        { folder: 'soundboard' },
        { folder: 'space-company' },
        { folder: 'spacegarden' },
        { folder: 'spelunky' },
        { folder: 'spinningrat' },
        { folder: 'ssurferbotleg' },
        { folder: 'starve' },
        { folder: 'station-141' },
        { folder: 'stationmeltdown', entry: 'Build/index.html' },
        { folder: 'stealingthediamond' },
        { folder: 'stick-duel-battle' },
        { folder: 'stick-merge' },
        { folder: 'stickman-boost' },
        { folder: 'stickman-golf' },
        { folder: 'stickman-hook' },
        { folder: 'Stickman-Survival' },
        { folder: 'stickwar' },
        { folder: 'stormthehouse2' },
        { folder: 'subway-surfers-ny' },
        { folder: 'superfowlist' },
        { folder: 'superhot' },
        { folder: 'surviv' },
        { folder: 'sushi-unroll' },
        { folder: 'swerve' },
        { folder: 'tactical-weapon-pack-2' },
        { folder: 'tacticalassasin2' },
        { folder: 'tanuki-sunset' },
        { folder: 'temple-run-2' },
        { folder: 'the-final-earth-2' },
        { folder: 'the-hotel' },
        { folder: 'thebattle' },
        { folder: 'theheist' },
        { folder: 'there-is-no-game' },
        { folder: 'thisistheonlylevel' },
        { folder: 'throwrocks' },
        { folder: 'tiny-fishing' },
        { folder: 'tiny-islands' },
        { folder: 'tosstheturtle' },
        { folder: 'townscaper' },
        { folder: 'Trimps' },
        { folder: 'tube-jumpers' },
        { folder: 'tunnel-rush' },
        { folder: 'tv-static' },
        { folder: 'twitch-tetris' },
        { folder: 'veloce' },
        { folder: 'vex3' },
        { folder: 'vex4' },
        { folder: 'vex6' },
        { folder: 'vex7' },
        { folder: 'waterworks' },
        { folder: 'weavesilk' },
        { folder: 'webcleaner' },
        { folder: 'webgl-fluid-simulation' },
        { folder: 'webretro', entry: 'info/index.html' },
        { folder: 'webxash' },
        { folder: 'win-the-whitehouse' },
        { folder: 'wolf2d' },
        { folder: 'wolf3d' },
        { folder: 'wordle' },
        { folder: 'worlds-hardest-game' },
        { folder: 'worlds-hardest-game-2' },
        { folder: 'wounded-summer-baby-edition' },
        { folder: 'xx142-b2exe' },
        { folder: 'yohoho' },
        { folder: 'yoshifabrication' },
        { folder: 'you-are-bezos' },
        { folder: 'zombs-royale' }
    ];

    function displayName(folder) {
        return folder.replace(/[-_]+/g, ' ').replace(/\b\w/g, function (letter) {
            return letter.toUpperCase();
        });
    }

    /* logo file name guess: lowercase, spaces become dashes */
    function slug(folder) {
        return folder.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9._-]/g, '');
    }

    var EXTS = ['png', 'jpg', 'jpeg', 'webp', 'PNG', 'JPG', 'JPEG', 'gif'];

    var grid = document.getElementById('gameGallery');
    if (!grid) return;

    games.forEach(function (game, index) {
        var enc = encodeURIComponent(game.folder);
        var base = 'Games/' + enc + '/';
        var entry = (game.entry || 'index.html').split('/').map(encodeURIComponent).join('/');
        var name = displayName(game.folder);

        var card = document.createElement('a');
        card.className = 'gl-card';
        card.href = base + entry;
        card.style.setProperty('--i', index);

        var art = document.createElement('span');
        art.className = 'gl-art';

        var image = document.createElement('img');
        var sources = [];
        if (game.image) sources.push('images/' + game.image);
        EXTS.forEach(function (ext) {
            sources.push('images/' + slug(game.folder) + '.' + ext);
        });
        sources.push(base + 'splash.png', base + 'splash.jpg', base + 'icon.png');

        var n = 0;
        image.onerror = function () {
            n++;
            if (n < sources.length) image.src = sources[n];
            else image.style.display = 'none';
        };
        image.src = sources[0];
        image.alt = '';
        image.loading = 'lazy';
        image.decoding = 'async';

        var play = document.createElement('span');
        play.className = 'gl-play';
        play.textContent = 'Play';

        var title = document.createElement('h3');
        title.textContent = name;

        art.appendChild(image);
        art.appendChild(play);
        card.appendChild(art);
        card.appendChild(title);
        grid.appendChild(card);
    });

})();